name: Echo commands
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: ${{github.ref}}
          path: '' #  Relative path under $GITHUB_WORKSPACE to place the repository
      - name: Echo commands
        run: |
          echo '::echo::on'
          ls ${{ github.workspace }}
