name: Read env vars
on:
  push:
    branches: [ main ]
jobs:
  read-env-vars:
    runs-on: ubuntu-latest
    steps:
    - name: Test env var read
      run: |
        echo "REPO-NAME=$(echo ${{ github.repository }} | awk -F / '{print $2}' | sed -e "s/:refs//")"
        echo "${{ github.repository_owner }}"
        echo "${{ env.REPO-NAME }}"
